<?php
/**
 * Initialize the custom theme options.
 */
add_action( 'admin_init', 'custom_theme_options' );

/**
 * Build the custom settings & update OptionTree.
 */
function custom_theme_options() {
  /**
   * Get a copy of the saved settings array. 
   */
  $saved_settings = get_option( 'option_tree_settings', array() );
  
  /**
   * Custom settings array that will eventually be 
   * passes to the OptionTree Settings API Class.
   */
  $custom_settings = array( 
    'contextual_help' => array( 
      'sidebar'       => ''
    ),
    'sections'        => array(
      array(
        'id'          => 'ads',
        'title'       => 'Ads'
      ), 
      array(
        'id'          => 'entertainment',
        'title'       => 'Entertainment'
      ),
      array(
        'id'          => 'arts-culture',
        'title'       => 'arts-culture'
      ),
      array(
        'id'          => 'community',
        'title'       => 'community'
      ),
      array(
        'id'          => 'food-dining',
        'title'       => 'food-dining'
      ),
      array(
        'id'          => 'qh-sensation',
        'title'       => 'qh-sensation'
      ),
      array(
        'id'          => 'sports',
        'title'       => 'sports'
      ),
      array(
        'id'          => 'movie',
        'title'       => 'movie'
      ),
      array(
        'id'          => 'about-qh',
        'title'       => 'about-qh'
      ),
      array(
        'id'          => 'reader',
        'title'       => 'Feature Reader'
      ),
      array(
        'id'          => 'facebook',
        'title'       => 'Facebook Settings'
      ),  
    ),
    'settings'        => array( 
      array(
        'id'          => 'ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'ads',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'entertainment_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'entertainment',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'arts-culture_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'arts-culture',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'community_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'community',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'food-dining_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'food-dining',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'qh-sensation_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'qh-sensation',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'sports_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'sports',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'movie_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'movie',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad1_url',
        'label'       => 'Ad 1 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad1_image',
        'label'       => 'Ad 1',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad2_url',
        'label'       => 'Ad 2 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad2_image',
        'label'       => 'Ad 2',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad3_url',
        'label'       => 'Ad 3 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad3_image',
        'label'       => 'Ad 3',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad4_url',
        'label'       => 'Ad 4 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad4_image',
        'label'       => 'Ad 4',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad5_url',
        'label'       => 'Ad 5 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad5_image',
        'label'       => 'Ad 5',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad6_url',
        'label'       => 'Ad 6 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad6_image',
        'label'       => 'Ad 6',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad7_url',
        'label'       => 'Ad 7 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad7_image',
        'label'       => 'Ad 7',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad8_url',
        'label'       => 'Ad 8 (url)',
        'desc'        => 'Enter the ad link url',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'about-qh_ad8_image',
        'label'       => 'Ad 8',
        'desc'        => 'Select the ad image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'about-qh',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'reader_image',
        'label'       => 'Reader Image',
        'desc'        => 'Select the Reader image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'reader',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'facebook_app_id',
        'label'       => 'Facebook App Id',
        'desc'        => 'Enter the Facebook App Id',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'facebook',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
    )
  );
  
  /* allow settings to be filtered before saving */
  $custom_settings = apply_filters( 'option_tree_settings_args', $custom_settings );
  
  /* settings are not the same update the DB */
  if ( $saved_settings !== $custom_settings ) {
    update_option( 'option_tree_settings', $custom_settings ); 
  }
  
}